#!/bin/sh
# Builds the inverse-design panel kernel (panel.c) to WebAssembly and embeds
# it in src/lib/inverse/panelKernel.js. Needs clang (with the wasm32 target)
# and wasm-ld (LLVM lld). Run from aerolab-web/:  sh native/build_panel.sh
set -e
cd "$(dirname "$0")"
FLAGS="--target=wasm32 -O3 -mbulk-memory -nostdlib -ffp-contract=off -Wl,--no-entry -Wl,--export-dynamic -Wl,--allow-undefined"
clang $FLAGS -o panel.wasm panel.c
clang $FLAGS -msimd128 -o panel_simd.wasm panel.c
node -e '
const fs = require("fs");
const b64 = (f) => fs.readFileSync(f).toString("base64");
fs.writeFileSync("../src/lib/inverse/panelKernel.js",
  "// Generated by native/build_panel.sh from native/panel.c. Do not edit.\n" +
  "export const PANEL_WASM = \"" + b64("panel.wasm") + "\";\n" +
  "export const PANEL_WASM_SIMD = \"" + b64("panel_simd.wasm") + "\";\n");
'
rm -f panel.wasm panel_simd.wasm
echo "wrote src/lib/inverse/panelKernel.js"
